#!/bin/bash

url=${SALT_URL:="http://salt/api/salt/"}
client=${SALT_CLIENT:="local"}
tgt="$1"
fun="$2"
shift; shift
arg="$@"

curl -sSi $url -d client="$client" -d tgt="$tgt" -d fun="$fun" -d arg="$arg"; echo
